### ISSUE TITLE
No clear way to change default path to MXE file

### ISSUE THREAD

**Issue by korgano** [dhavard/ValkyrieEdit#1] opened 2015-07-25 14:12 UTC
I've got my entire Steam Library (including Valkyria Chronicles) installed to a secondary HDD. The program says I need to provide a path, but I can't paste the file path to MXE file, and typing in "-help" only generates a text file with "-help" in it. There are also no obvious external config files that I can use to set the correct path. What am I supposed to do?

**Comment by dhavard** [comment] 2015-07-25 17:00
What operation system are you on? I'm assuming windows.

I also have my Steam Library on a secondary SSD, when you provide a path, simply provide the Drive letter such as follows:

> ValkyrieEdit.exe D:\my\path\to\steam\Valkyria Chronicles\data\mx\game_info_game_param.mxe

Simply add a "-t" or "-s" to the above to run it in test or save mode respectively.

As for the "-help" command, it should look as follows:

> ValkyrieEdit.exe -help

It should output text to the console, it definitely should not be generating a file. What is the name of the file being generated in your experience? I can't seem to reproduce this issue as described.

Also, if you were using the prebuilt binaries, you were using an older version of the application. I have updated the binaries to hopefully resolve your issue that way as well.

Additionally, I've added the help.txt to the solution. You can view the help text here:
https://github.com/dhavard/ValkyrieEdit/blob/master/ValkyrieEdit/help.txt

Let me know if I can close this issue, or if the issue persists. In general, if I can't reproduce (as in this issue) and I don't hear back for a week or so, I'll assume its resolved ^_^

**Comment by korgano** [comment] 2015-07-25 18:39
Okay, I managed to get it working. Three things though:
-If you mess up your commands, it'll generate a "target.txt" file with the thing you typed (thankfully, this is overwritten by the newest error generating a new target.txt)
-The lack of copy/paste ability means that you get a LOT of typos generating a target.txt
-The help.txt isn't formatted well at all when viewed in Notepad.

**Comment by dhavard** [comment] 2015-07-25 20:08
Thank you for the feedback!
- Ahh, target.txt is a way of generating a 'cache' of the file you are working on (that way you don't have to keep telling it to use a given file); the fact that unrecognized commands end up being generated into the target.txt file is because it assumes you are trying to tell it about a file with your command. I'll make a change where if it doesn't recognize an argument that starts with a '-' it will assume you typoed a command.
- Copy / paste in console applications is controlled by your operating system / console program. If you are using window's command prompt, you can copy as normal from wherever you are copying from... and then paste in your command prompt by right clicking and selecting 'paste.'
  Reference the following for a "hotkey"-ish way of doing this as well:
  http://superuser.com/questions/16313/keyboard-shortcut-to-paste-in-windows-command-prompt
- Looks fine to me in Notepad, Visual Studio, Notepad++, and emacs. Also looks fine if you just look at it in Chrome out of the github repo. Not that it is perfect though, so **if you feel there is a better version of this file... feel free to make one and submit either a pull request, or create another issue to update it.** As a programmer, I look at stuff with crap format / binary all day, so creating something with a sane/nice format isn't my forte ^_^

### I'll make a change where if it doesn't recognize an argument that starts with a '-' it will assume you typoed a command.

**Comment by dhavard** [comment] 2015-07-25 20:09
Re-opening pending commit actually.

**Comment by dhavard** [comment] 2015-07-25 22:49
Newest code and binaries should resolve the problem with supplying arguments that are not understood.

**Closed as completed by dhavard** 2015-07-25 22:49 UTC
